name: task_list_app
description: Task list application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  dio: ^5.2.1+1

  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.3

  freezed_annotation: ^2.2.0

  
  go_router: ^8.0.3
  hooks_riverpod: ^2.1.3
  intl: ^0.18.0
  i18n: ^4.0.3
  json_annotation: ^4.7.0
  
dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.2
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
